name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Latest Ubuntu Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Github secret containing Azure credentials in JSON format

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/initial-requirements

    - name: Terraform Plan
      run: terraform plan -out=tfplan -var "bastion_username=${{ secrets.BASTION_USERNAME }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      working-directory: ./terraform/initial-requirements

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform/initial-requirements